# Generated by Django 4.2.11 on 2024-03-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='netto',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='product',
            name='nut_value',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
